### PR TITLE
Enable mobile swipe (react-swipeable)

### PR DESCRIPTION
**Pull request by bchristie**
Wrapped Slide in a swipe-enabled component and passed on references to [next/prev]Slide actions. (may be better to wrap entire window over just code preview?)

Admittedly a React novice, so if this looks hacky--it probably is. ;-)

### CODE REVIEW

**Comment by bchristie** [comment]
BTW, should also be a solution to #37

**Comment by pomber** [comment]
Niiice.
Could you wrap the <Slide> component inside of the <Swipeable> instead of <pre>? I want to keep the Slide component small

**Comment by Brad-Christie** [comment]
> Niiice.
> Could you wrap the component inside of the instead of
> 
> ? I want to keep the Slide component small

Not sure I understand (word missing due to markdown parser?) You may be asking for a refactor I already was thinking of doing: Migrating `<Slideable>` up into `history.js` to avoid plumbing into the Slide component. Is that in the ballpark?

**Comment by pomber** [comment]
Yes, sorry, markdown fail.
I meant what you said: move Slideable to history.js and leave slide.js as it was :slightly_smiling_face:

**Comment by bchristie** [comment]
Please see PR #50

**Pull request closed without merging**
